export const canonicalBooks = [
  ['GEN', 'Genesis', ['Ge', 'Gen'], 50],
  ['EXO', 'Exodus', ['Ex', 'Exod'], 40],
  ['LEV', 'Leviticus', ['Le', 'Lev'], 27],
  ['NUM', 'Numbers', ['Nu', 'Num'], 36],
  ['DEU', 'Deuteronomy', ['De', 'Deut'], 34],
  ['JOS', 'Joshua', ['Jos', 'Josh'], 24],
  ['JDG', 'Judges', ['Jdg', 'Judg'], 21],
  ['RUT', 'Ruth', ['Ru', 'Ruth'], 4],
  ['1SA', '1 Samuel', ['1 Sa', '1 Sam', 'I Samuel'], 31],
  ['2SA', '2 Samuel', ['2 Sa', '2 Sam', 'II Samuel'], 24],
  ['1KI', '1 Kings', ['1 Ki', '1 Kgs', 'I Kings'], 22],
  ['2KI', '2 Kings', ['2 Ki', '2 Kgs', 'II Kings'], 25],
  ['1CH', '1 Chronicles', ['1 Ch', '1 Chr', 'I Chronicles'], 29],
  ['2CH', '2 Chronicles', ['2 Ch', '2 Chr', 'II Chronicles'], 36],
  ['EZR', 'Ezra', ['Ezr', 'Ezra'], 10],
  ['NEH', 'Nehemiah', ['Ne', 'Neh'], 13],
  ['EST', 'Esther', ['Es', 'Est'], 10],
  ['JOB', 'Job', ['Job'], 42],
  ['PSA', 'Psalms', ['Ps', 'Psalm', 'Psa'], 150],
  ['PRO', 'Proverbs', ['Pr', 'Prov'], 31],
  ['ECC', 'Ecclesiastes', ['Ec', 'Ecc'], 12],
  ['SNG', 'Song of Songs', ['Song', 'Song of Solomon', 'Sos'], 8],
  ['ISA', 'Isaiah', ['Isa', 'Is'], 66],
  ['JER', 'Jeremiah', ['Jer', 'Je'], 52],
  ['LAM', 'Lamentations', ['La', 'Lam'], 5],
  ['EZK', 'Ezekiel', ['Eze', 'Ezek'], 48],
  ['DAN', 'Daniel', ['Da', 'Dan'], 12],
  ['HOS', 'Hosea', ['Ho', 'Hos'], 14],
  ['JOL', 'Joel', ['Joe', 'Joel'], 3],
  ['AMO', 'Amos', ['Am', 'Amos'], 9],
  ['OBA', 'Obadiah', ['Ob', 'Obad'], 1],
  ['JON', 'Jonah', ['Jon', 'Jona'], 4],
  ['MIC', 'Micah', ['Mic', 'Mi'], 7],
  ['NAM', 'Nahum', ['Na', 'Nah'], 3],
  ['HAB', 'Habakkuk', ['Hab', 'Hb'], 3],
  ['ZEP', 'Zephaniah', ['Zep', 'Zeph'], 3],
  ['HAG', 'Haggai', ['Hag', 'Hg'], 2],
  ['ZEC', 'Zechariah', ['Zec', 'Zech'], 14],
  ['MAL', 'Malachi', ['Mal', 'Ml'], 4],
  ['MAT', 'Matthew', ['Mt', 'Matt'], 28],
  ['MRK', 'Mark', ['Mk', 'Mrk'], 16],
  ['LUK', 'Luke', ['Lk', 'Luk'], 24],
  ['JHN', 'John', ['Jn', 'Jhn'], 21],
  ['ACT', 'Acts', ['Ac', 'Acts'], 28],
  ['ROM', 'Romans', ['Ro', 'Rom'], 16],
  ['1CO', '1 Corinthians', ['1 Co', '1 Cor', 'I Corinthians'], 16],
  ['2CO', '2 Corinthians', ['2 Co', '2 Cor', 'II Corinthians'], 13],
  ['GAL', 'Galatians', ['Ga', 'Gal'], 6],
  ['EPH', 'Ephesians', ['Eph', 'Ep'], 6],
  ['PHP', 'Philippians', ['Php', 'Phil'], 4],
  ['COL', 'Colossians', ['Col'], 4],
  ['1TH', '1 Thessalonians', ['1 Th', '1 Thess'], 5],
  ['2TH', '2 Thessalonians', ['2 Th', '2 Thess'], 3],
  ['1TI', '1 Timothy', ['1 Ti', '1 Tim'], 6],
  ['2TI', '2 Timothy', ['2 Ti', '2 Tim'], 4],
  ['TIT', 'Titus', ['Tit'], 3],
  ['PHM', 'Philemon', ['Phm', 'Philem'], 1],
  ['HEB', 'Hebrews', ['Heb'], 13],
  ['JAS', 'James', ['Jas', 'Jam'], 5],
  ['1PE', '1 Peter', ['1 Pe', '1 Pet'], 5],
  ['2PE', '2 Peter', ['2 Pe', '2 Pet'], 3],
  ['1JN', '1 John', ['1 Jn', '1 John'], 5],
  ['2JN', '2 John', ['2 Jn', '2 John'], 1],
  ['3JN', '3 John', ['3 Jn', '3 John'], 1],
  ['JUD', 'Jude', ['Jud', 'Jude'], 1],
  ['REV', 'Revelation', ['Re', 'Rev', 'Apocalypse'], 22],
] as const;

export type CanonicalBookId = (typeof canonicalBooks)[number][0];

export type CanonicalBookDefinition = {
  readonly id: CanonicalBookId;
  readonly name: string;
  readonly aliases: readonly string[];
  readonly chapterCount: number;
};

export const canonicalBookDefinitions: readonly CanonicalBookDefinition[] =
  canonicalBooks.map(([id, name, aliases, chapterCount]) => ({
    id,
    name,
    aliases,
    chapterCount,
  }));
